- name: Deploy Flask Application
  hosts: web
  become: true

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3-venv
          - python3-pip
          - ufw
        state: present

    - name: Create Python virtual environment
      shell: |
        if [ ! -d "/home/kali/venv" ]; then
          python3 -m venv /home/kali/venv
        fi

    - name: Clone Flask application repository
      git:
        repo: 'https://github.com/abdorhl/ftest.git'
        dest: '/home/kali/ftest'
        version: 'master'

    - name: Install Python packages from requirements.txt
      command: "/home/kali/venv/bin/pip install -r /home/kali/ftest/requirements.txt"
      become_user: kali

    - name: Allow SSH and HTTP traffic
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - '22'
        - '80'

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Create a systemd service file for the Flask app
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          User=kali
          WorkingDirectory=/home/kali/ftest
          Environment="PATH=/home/kali/venv/bin"
          ExecStart=/home/kali/venv/bin/gunicorn --bind 0.0.0.0:80 app:app
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Flask app service
      systemd:
        name: flaskapp
        state: started
        enabled: true
